#!/usr/bin/env node

// Copyright (c) 2012, Srikumar K. S.
// Licensed for use and redistribution under the MIT license.
// See http://www.opensource.org/licenses/mit-license.php
//
// Simple global namespace package manager.
// Java style packages.
// Usage: 
//  Package names are in the reverse dns form 
//  - ex: "com.nishabdam.sample-manager".
//
// Functions:
//  package(name) -> 
//      Returns the currently loaded package of the given name.
//  package(name, definition) -> 
//      "definition" is a function that is called. The
//      return value of the function gives the package object. If definition itself
//      is an object, then it becomes the package value directly.
//  package(name, dependencies, definition) ->
//      "dependencies" is an array. This causes all the dependencies to
//      be loaded first. Once that is done, the definition function is
//      called with an argument list corresponding to the given array
//      of dependencies.
//
//  Utilities:
//   package.aliases({ name1: "com.blah.bling.SophisticatedName1", ...});
//      Defines aliases for long package names. The aliases are global.
//
//   package.config({
//      "com.where.packageName": { url: "where/dir/file.js", alias: "name" },
//      ...
//   })
//      The url can refer to a relative path or an absolute url.
//      If the 'url' key is specified instead of 'path', then the package
//      is fetched using http, even in Node.js environment.

var packagefn = (function (out) {

    var packages = {};
    // Maps package names of the form "com.blah.bling" to package objects a.k.a. "modules".

    var loading = {};
    // Every package that has started loading, but hasn't finished yet
    // will have its package name registered here.

    var onloads = {};
    // Maps complete package names to an array of callbacks to be called when the
    // package finished loading. The callbacks all take the package object as a
    // single parameter.

    var config = {};
    // Maps full package names to objects of the form -
    //      { path: "path/to/package/file.js"
    //      , url: "http://somewhere.com/somefile.js"  // Overrides 'path'
    //      , alias: "shortname"
    //      }

    var loadOrder = {};
    // Maps package name to number indicating when it was loaded.

    var aliases = {}; // Maps short names to full package names.

    // Add a special generic configuration for github.
    // If you have a package name of the form - "github.USERNAME.PROJECTNAME.x.y.z",
    // it will be expected to be located at the URL -
    //      "https://raw.github.com/USERNAME/PROJECTNAME/master/x/y/z.js"
    // .. and "github.USERNAME.PROJECTNAME" maps to
    //      "https://raw.github.com/USERNAME/PROJECTNAME/master/PROJECTNAME.js"
    config['github.*'] = function (components) {
        if (components.length < 2) {
            // Needs at least username, projectname and a filename.
            return undefined;
        }

        var username = components[0];
        var projectname = components[1];
        var path = (components.length === 2 ? projectname : components.slice(2).join('/')) + '.js';

        return {
            url: ('https://raw.github.com/' + username + '/' + projectname + '/master/' + path)
        };
    };

    // Some common external packages used.
    config['jQuery'] = {
        external: {
            url: 'http://code.jquery.com/jquery-1.7.2.js',
            dependsOn: [],
            depNames: [],
            name: '$'
        }
    };
    config['Underscore'] = {
        external: {
            url: 'https://raw.github.com/documentcloud/underscore/master/underscore.js',
            dependsOn: [],
            depNames: [],
            name: '_'
        }
    };
    config['Backbone'] = {
        external: {
            url: 'https://raw.github.com/documentcloud/backbone/master/backbone.js',
            dependsOn: ['Underscore'],
            depNames: ['_'],
            name: 'Backbone'
        }
    };
    config['Prototype'] = {
        external: {
            url: 'https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js',
            dependsOn: [],
            depNames: [],
            name: 'Prototype'
        }
    };
    config['MooTools'] = {
        external: {
            url: 'http://mootools.net/download/get/mootools-core-1.4.5-full-nocompat.js',
            name: 'MooTools',
            dependsOn: [],
            depNames: []
        }
    };

  
    // Valid package names are those that are not any of
    // the builtin members of Function objects in JS,
    // which includes raw objects as well. This excludes
    // stuff like 'constructor', 'toString', etc. as package
    // names. It returns the name if valid, throws an exception
    // if not valid.
    var validPkgName = (function () {
        function dummyFn() {}
        return function (n) {
            if (dummyFn[n]) {
                throw new Error('Invalid package component name [' + n + ']');
            } else {
                return n;
            }
        };
    }());

    // Search through the package hierarchy for a
    // configuration. A configuration can be either an object
    // with 'url' or 'path' fields, or a function which will
    // return such an object when passed the subpackage 
    // components as an array.
    function findConfig(pkgname) {
        var i, N, part, partArr, cfg;
        var components = pkgname.split('.');
        for (i = 0, N = components.length; i < N; ++i) {
            partArr = components.slice(0, components.length - i);
            if (i > 0) {
                partArr.push('*'); // We're searching parent packages.
            }
            part = partArr.join('.');
            cfg = config[part];
            if (!cfg) {
                continue;
            }
            if (cfg.constructor === Function) {
                cfg = cfg(components.slice(components.length - i));
                if (cfg) {
                    break;
                }
            } else if (i === 0 && cfg.constructor === Object) {
                break;
            }
        }
        if (cfg) {
            config[pkgname] = cfg; // Cache the config.
        }
        return cfg;
    }


    // Gets path specified in config, or derives a path
    // from the package name by replacing '.' with '/'.
    function packagePath(name) {
        var cfg = findConfig(name);
        if (cfg) {
            return cfg.path;
        } else {
            return name.replace(/\./g, '/') + '.js';
        }
    }

    // Returns url if absolute one is specified.
    function packageURL(name) {
        var cfg = findConfig(name);
        if (cfg && cfg.url && /^https?:\/\//.test(cfg.url)) {
            return cfg.url;
        } else {
            return null;
        }
    }

    function knownPackage(name) {
        return packages[name] || (name === '#global' ? "package.__global__" : undefined);
    }

    function trueName(name) {
        if (/^\./.test(name)) {
            name = packagefn.__parent + name;
        }
        return name in aliases ? aliases[name] : name;
    }

    function pseudoPackage(name) {
        return name.charAt(0) === '#';
    }

    function definePackageFromSource(name, source) {
        loadConfig(name);
        var closure = eval('(function (package) {\n' + source + ';\n})');
        packagefn.__config_name__ = name;
        closure(packagefn, name);
        return packages[name];
    }

    function replaceAll(str, pat, subst) {
        while (pat.test(str)) {
            str = str.replace(pat, subst);
        }
        return str;
    }

    function fullname(name) {
        return ['package._', replaceAll(name, /\-/, '_')].join('.');
    }

    // Inside a package definition function, "this"
    // refers to the current package object so you can
    // setup exports by assigning properties to the
    // "this" object. If you don't have a return statement
    // in the package definition function, or you return 
    // 'undefined', the this object will be used as the
    // package definition. Otherwise the return value will
    // be used.
    function defWithFallback(pname, pkg, definition, dependencies) {
        var pname_ = fullname(pname);
        declPkg(pname);

        if (definition && definition.constructor === Function) {
            out.write(pname_ + ' = (');
            out.write(definition.toString() + ').call(' + [pname_].concat(dependencies).join(', ') + ') || ' + pname_ + ';\n');
        } else {
            out.write(pname_ + ' = (' + JSON.stringify(definition) + ');\n');
        }
        return pname_;
    }

    function declPkg(name) {
        var name_ = fullname(name);
        name.split('.').forEach(function (part, i, parts) {
            validPkgName(part);
            var n = parts.slice(0, i+1).join('.');
            if (!packages[n]) {
                var n_ = fullname(n);
                out.write(n_ + ' = ' + n_ + ' || {};\n');
                packages[n] = n_;
            }
        });
        return packages[name] = name_;
    }

    function definePackage(name, definition, dependencies) {
        packagefn.__parent = name.replace(/\.[^\.]+$/, '');
        var p = declPkg(name);
        packages[name] = defWithFallback(name, p, definition, dependencies);
        return onPackageLoaded(name);
    }

    function addOnLoad(name, callback) {
        if (name in onloads) {
            onloads[name].push(callback);
        } else {
            onloads[name] = [callback];
        }
    }

    var delay = (function () {
        try {
            return process.nextTick;
        } catch (e) {
            return function (proc) { setTimeout(proc, 0); };
        }
    }());

    function with_package_in_browser(name, callback) {
        // Expected to be loaded.
        var p = knownPackage(name);
        if (p) {
            // Package already loaded.
            delay(function () { callback(p); });
        } else if (loading[name]) {
            // Package started loading already.
            addOnLoad(name, callback);
        } else {
            // Need to load package.
            loading[name] = true;
            addOnLoad(name, callback);
            if (!pseudoPackage(name)) {
                var cfg = findConfig(name);
                if (cfg && cfg.external) {
                    loadExternalModuleFromURL(name, cfg.external.url, cfg.external.dependsOn, cfg.external.depNames, cfg.external.name);
                } else {
                    var script = document.createElement('script');
                    script.setAttribute('src', packagePath(name));
                    document.head.insertAdjacentElement('beforeend', script);
                }
            }
        }
    }

    function with_package_in_fs(name, callback) {
        var p = knownPackage(name);
        var source, closure, where;
        if (p) {
            // Package loaded already.
            delay(function () { callback(p); });
        } else if (loading[name]) {
            // Package started loading already.
            addOnLoad(name, callback);
        } else {
            // Need to load package.
            loading[name] = true;
            addOnLoad(name, callback);
            if (!pseudoPackage(name)) {
                var cfg = findConfig(name);
                if (cfg && cfg.external) {
                    loadExternalModuleFromURL(name, cfg.external.url, cfg.external.dependsOn, cfg.external.depNames, cfg.external.name);
                } else {
                    where = packageURL(name);
                    if (where) {
                        loadPackageFromURL(name, where);
                    } else {
                        where = packagePath(name);
                        loadPackageFromDisk(name, where);
                    }
                }
            }
        }
    }

    function fetch_url_async_in_browser(url, callback, errback) {
        var req = new XMLHttpRequest();
        req.open('GET', url, true);
        req.onload = function () {
            if (req.status === 200) {
                callback(packagefn, url, req.responseText);
            } else if (errback) {
                errback("Module path [" + url + "] not found.");
            }
        };
        req.send();
    }

    function fetch_url_async(url, callback, errback) {
        var urlp = require('url').parse(url);
        if (urlp.protocol === 'http:' || urlp.protocol === 'https:') {
            urlp.headers = {'Accept-Encoding': 'identity'};
            require(urlp.protocol.split(':')[0]).get(urlp, function (res) {
                var source = "";
                res.setEncoding('utf8');
                res.on('data', function (chunk) {
                    source += chunk;
                });
                res.on('end', function () {
                    callback(packagefn, url, source);
                });
                res.on('error', function (err) {
                    if (errback) {
                        errback(err);
                    }
                });
            }).on('error', function (err) {
                if (errback) {
                    errback(err);
                }
            });
        } else {
            return require('fs').readFile(url, 'utf8', function (err, data) {
                if (err) {
                    if (errback) {
                        errback(err);
                    }
                } else {
                    callback(packagefn, url, data);
                }
            });
        }
    }

    var with_package, fetch;
    try {
        if (window.navigator) {
            // In browser
            with_package = with_package_in_browser;
            fetch = fetch_url_async_in_browser;
        }
    } catch (e) {
        // In Node.js
        with_package = with_package_in_fs;
        fetch = fetch_url_async;
    }

    function loadPackageFromURL(name, url) {
        fetch_url_async(url, function (packagefn, url, source) {
            package.__CONFIG__ = {url: url};
            definePackageFromSource(name, source);
        }, function (err) {
            console.error(err);
        });
    }

    var listingPkgSuffix = /\.__listing__$/;
    var listingFileSuffix = /__listing__\.js$/;

    function loadPackageFromDisk(name, where) {
        var fs = require('fs');
        var source, dirLoc, dirContents, parentPkg, subDirs, subDirCount;

        try {
            source = fs.readFileSync(where, 'utf8');
            packagefn.__CONFIG__ = {path: where};
            definePackageFromSource(name, source);
        } catch (e) {
            if (listingPkgSuffix.test(name)) {
                // A listing entry failed. In this case, we can find
                // out the directory contents automatically. So do that.
                dirLoc = where.replace(listingFileSuffix, '');
                dirContents = fs.readdirSync(dirLoc);
                parentPkg = name.replace(listingPkgSuffix, '');
                packages[name] = 
                    dirContents.filter(function (f) { return /\.js$/.test(f); })
                    .map(function (f) { 
                        var fname = f.replace(/\.js$/, ''); 
                        var cfg = {};
                        cfg[parentPkg + '.' + fname] = {path: dirLoc + f};
                        packagefn.config(cfg);
                        return fname;
                    });

                subDirs = dirContents.filter(function (f) {
                    return fs.statSync(where.replace(listingFileSuffix, f)).isDirectory();
                });
                if (subDirs.length === 0) {
                    onPackageLoaded(name);
                } else {
                    subDirCount = 0;
                    // Recursively load sub directories.
                    subDirs.forEach(function (f) {
                        var fname = name.replace(/__listing__$/, f) + '.__listing__';
                        delay(function () {
                            with_package(fname, function (p) {
                                ++subDirCount;
                                if (subDirCount === subDirs.length) {
                                    onPackageLoaded(name);
                                }
                            });
                        });
                    });
                }
            } else {
                console.error("Failed to load package [" + name + "] from [" + where + "]");
                console.error("Current configuration = ");
                console.error(config);
            }
        }
    }

    // An external module is something that doesn't use package to wrap it.
    // This includes libraries such as jquery, backbone, underscore and any
    // other that wishes to be directly used in an app using a <script> url.
    function loadExternalModuleFromURL(pkgname, url, depPkgNames, depVarNames, exportedName) {
        packagefn.fetch(url, function (package, url, source) {
            package(pkgname, ['#global'].concat(depPkgNames), 
                eval('(function (' + ['__window__'].concat(depVarNames).join(',') + ') {\n'
                    + 'var module = {exports: {}}, exports = module.exports;\n'
                    + 'var window = Object.create(__window__);\n'
                    + depVarNames.map(function (n) { return 'window.' + n + ' = ' + n + ';\n'; }).join('')
                    + 'return (function () {\n'
                        + source
                        + '\nreturn this.' + exportedName + ' || module.exports;\n'
                        + '}).call(window);\n'
                    + '})'));
        });
    }
    
    // If you load a package named 'blah.bling.meow',
    // then you can get the package in a number of ways -
    //      package('blah.bling.meow')
    //      package('blah.bling.*').meow
    //      package('blah.*').bling.meow
    //      package('*').blah.bling.meow
    //  This function sets up all those alternative paths.
    function setPackagePatterns(components, p) {
        components.forEach(function (comp, i) {
            validPkgName(comp);
            var n = components.slice(0, i).join('.');
            packages[n + (i > 0 ? '.*' : '*')] = n;
        });
    }

    function onPackageLoaded(name) {
        var p = packages[name];
        var callbacks = onloads[name];
        // Add the package to pattern packages as well.
        var components = name.split('.');
        components[0] = trueName(components[0]);
        setPackagePatterns(components, p);
        delete loading[name];

        // Store the load order so that we can optimize package load
        // sequence.
        loadOrder[name] = packagefn.loadOrder++;

//        console.log("package " + name + " loaded");
        if (callbacks && callbacks.length > 0) {
            delete onloads[name];
            callbacks.forEach(function (cb) { 
                delay(function () { 
                    cb(p); 
                }); 
            });
        }
        return p;
    }

    function relativePackagePath(path, pkg) {
        var components = path.split('/');
        // The last component of pkg after the final period is taken
        // as the name of the file, with a js suffix. For example,
        // if pkg is "canine.dog.bowow", then the right hand side
        // of the assignment below will evaluate to "bowow.js".
        components[components.length - 1] = pkg.match(/\.([^\.]+)$/)[1] + '.js';
        return components.join('/');
    }

    function loadConfig(pname) {
        if (!config[pname] && packagefn.__CONFIG__) {
            var cfg = {};
            cfg[pname] = {url: packagefn.__CONFIG__.url, path: packagefn.__CONFIG__.path};
            packagefn.config(cfg);
        }
    }

    function package3(name, dependencies, definition) {
        var depPackages = [];
        var count = 0;
        var pname = trueName(validPkgName(name));

        loadConfig(pname);

        var pnamecfg = findConfig(pname);

        if (dependencies.length > 0) {
            dependencies.forEach(function (dep, i) {
                var tname = trueName(dep);
                var tnamecfg;

                function onePkgLoaded(p) {
                    depPackages[i] = p;
                    ++count;
                    if (count === dependencies.length) {
                        definePackage(pname, definition, depPackages);
                    }
                }

                if (/^\.[^\.]+$/.test(dep)) {
                    // Relative package name starting with a period.
                    // Auto expand it.
                    dep = pname.replace(/\.[^\.]+$/, dep);
                    tname = trueName(dep);
                    tnamecfg = findConfig(tname);

                    // IMPORTANT:
                    // If pname has a config and this one doesn't, then
                    // assume it is going to be served up from the same location.
                    // This is an important simplification that lets you omit
                    // parent package prefixes of dependencies.
                    if (pnamecfg && !tnamecfg) {
                        config[tname] = {};
                        if (pnamecfg.path) {
                            config[tname].path = relativePackagePath(pnamecfg.path, dep);
                        }
                        if (pnamecfg.url) {
                            config[tname].url = relativePackagePath(pnamecfg.url, dep);
                        }
                    }
                }
                
                if (/\.\*$/.test(tname)) {
                    var listing =  tname.replace(/\*$/, '__listing__');
                    with_package(listing, function (p) {
                        var subPkgs = {};
                        var subPkgCount = 0;
                        p.forEach(function (subPkgName) {
                            with_package(tname.replace(/\*$/, subPkgName), function (sp) {
                                subPkgs[subPkgName] = sp;
                                ++subPkgCount;
                                if (subPkgCount === p.length) {
                                    onePkgLoaded(subPkgs);
                                }
                            });
                        });
                    });
                } else {
                    with_package(tname, onePkgLoaded);
                }
            });
            return undefined;
        } else {
            return definePackage(pname, definition, []);
        }
    }

    function package2(name, definition) {
        if (name.constructor === Array) {
            // name is actuall the array of dependencies, since
            // no name has been given.
            return package3(package.__config_name__, arguments[0], definition);
        } else {
            var tname = trueName(validPkgName(name));
            loadConfig(tname);
            return definePackage(tname, definition, []);
        }
    }

    function package1(name) {
        if (name.constructor === Function) {
            // Pure package definition with default name and no dependencies.
            return package3(package.__config_name__, [], arguments[0]);
        } else {
            name = trueName(validPkgName(name));
            return packages[name];
        }
    }

    function packagefn() {
        switch (arguments.length) {
            case 1: return package1(arguments[0]);
            case 2: return package2(arguments[0], arguments[1]);
            case 3: return package3(arguments[0], arguments[1], arguments[2]);
            default: throw "Invalid number of arguments.";
        }
    }

    function defAlias(name, p) {
        aliases[name] = p;
        var pobj = packages[p];
        if (pobj) {
            packages[name] = pobj;
            onPackageLoaded(name);
        } else {
            addOnLoad(p, function (pobj) {
                packages[name] = pobj;
                onPackageLoaded(name);
            });
        }
    }

    packagefn.config = function (setupInfo) {
        var i;
        for (var p in setupInfo) {
            i = config[p] = setupInfo[p];
            i.alias && defAlias(i.alias, p);
        }
    };

    packagefn.aliases = function (name2package) {
        for (var a in name2package) {
            defAlias(a, name2package[a]);
        }
    };

    packagefn.fetch = fetch;

    packagefn.declare = function (packagesThatWillBeDefined) {
        packagesThatWillBeDefined.forEach(function (pname) {
            var pnameres = trueName(pname);
            if (!knownPackage(pnameres)) {
                loading[pname] = true;
                loading[pnameres] = true;
            }
        });
    };

    packagefn.external = function (pkgname, exportedName, url, dependsOn, depNames) {
        var cfg = {};
        cfg[pkgname] = { external: {
            url: url,
            dependsOn: dependsOn || [],
            depNames: depNames || dependsOn || [],
            name: exportedName
        }};
        packagefn.config(cfg);
    };

    packagefn.loadOrder = 1;

    return packagefn;
}(process.stdout));

var fs = require('fs');

function package(name) {
    var hyphen = /\-/g;
    while (hyphen.test(name)) {
        name = name.replace(hyphen, '_');
    }
    name = name.replace(/\.?\*$/, '');
    var root = package._;
    name.split('.').forEach(function (part) {
        root = root[part];
    });
    return root;
}

function main() {
    process.stdout.write(package.toString() + '\n');
    process.stdout.write('package.__global__ = (function () {\n'
        + 'try { window.document; return window; } catch (e) {}\n'
        + 'try { global.require; return global; } catch (e) {}\n'
        + '}());\n');
    process.stdout.write('package._ = {};\n'); // package._ contains all packages.
    process.stdout.write('try { window["package"] = package; } catch (e) {}\n');
    process.stdout.write('try { module.exports = package; } catch (e) {}\n');
    process.argv.forEach(function (arg, i) {
        if (i >= 2) {
            var source = fs.readFileSync(process.argv[i], 'utf8');
            packagefn.__CONFIG__ = {path: process.argv[i]};
            eval('(function (package) {\n' + source + '\n})')(packagefn);
        }
    });
}

// Call without arguments to fetch ".package.js" file containing configuration 
// about known packages.
if (process.argv.length <= 2) {
    console.error('Usage: build [build-config.js] file1.js file2.js ... > concatenated.js');
} else {
    main();
}
